#!/bin/sh

wait_for() {
  for i in `seq 30` ; do
	  curl -f ${ELASTICSEARCH_URL}:${ELASTICSEARCH_PORT}/_cluster/health > /dev/null 2>&1
    result=$?
    if [ $result -eq 0 ] ; then
      if [ $# -gt 0 ] ; then
        exec "$@"
      fi
      exit 0
    fi
    echo "* Waiting for Elasticsearch ${ELASTICSEARCH_URL}:${ELASTICSEARCH_PORT} ($i/30)"
    sleep 2
  done
  echo "Operation timed out" >&2
  exit 1
}

wait_for "$@"
